project_id = "zjmnlelqoiclkbrqefyv"

[functions.send-push-notification]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = false

[functions.get-weather]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.create-customer-portal-session]
verify_jwt = true

[functions.create-payment-intent]
verify_jwt = true

[functions.create-subscription]
verify_jwt = true

[functions.get-stripe-config]
verify_jwt = false

[functions.geocode-address]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = true
