project_id = "zjmnlelqoiclkbrqefyv"

[functions.send-push-notification]
verify_jwt = true

[functions.server-time]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.get-weather]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.create-customer-portal-session]
verify_jwt = true

[functions.create-payment-intent]
verify_jwt = true

[functions.create-subscription]
verify_jwt = true

[functions.get-stripe-config]
verify_jwt = false

[functions.geocode-address]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = true

[functions.send-verification-reminder]
verify_jwt = false

[functions.submit-support-ticket]
verify_jwt = false

[functions.send-ticket-email]
verify_jwt = true

[functions.send-notification-email]
verify_jwt = false

[functions.process-trip-reminders]
verify_jwt = false

[functions.generate-agora-token]
verify_jwt = true

[functions.create-daily-room]
verify_jwt = true

[functions.delete-account]
verify_jwt = false

[functions.process-challenge-reminders]
verify_jwt = false

[functions.photo-challenge-checkout]
verify_jwt = true

[functions.test-email]
verify_jwt = false

[functions.seed-world-records]
verify_jwt = false
