
UPDATE public.fish_species SET scientific_name = data.sci
FROM (VALUES
  ('African Pompano', 'Alectis ciliaris'),
  ('Albacore Tuna', 'Thunnus alalunga'),
  ('Alligator Gar', 'Atractosteus spatula'),
  ('Amberjack', 'Seriola dumerili'),
  ('Arapaima', 'Arapaima gigas'),
  ('Arctic Char', 'Salvelinus alpinus'),
  ('Atlantic Salmon', 'Salmo salar'),
  ('Bigeye Tuna', 'Thunnus obesus'),
  ('Black Crappie', 'Pomoxis nigromaculatus'),
  ('Black Drum', 'Pogonias cromis'),
  ('Black Grouper', 'Mycteroperca bonaci'),
  ('Black Marlin', 'Istiompax indica'),
  ('Blackfin Tuna', 'Thunnus atlanticus'),
  ('Blacktip Shark', 'Carcharhinus limbatus'),
  ('Blue Catfish', 'Ictalurus furcatus'),
  ('Blue Marlin', 'Makaira nigricans'),
  ('Bluefin Tuna', 'Thunnus thynnus'),
  ('Bluegill', 'Lepomis macrochirus'),
  ('Bonefish', 'Albula vulpes'),
  ('Brook Trout', 'Salvelinus fontinalis'),
  ('Brown Trout', 'Salmo trutta'),
  ('Bull Shark', 'Carcharhinus leucas'),
  ('Bullhead Catfish', 'Ameiurus nebulosus'),
  ('Carp', 'Cyprinus carpio'),
  ('Catfish', 'Siluriformes'),
  ('Cero Mackerel', 'Scomberomorus regalis'),
  ('Chain Pickerel', 'Esox niger'),
  ('Channel Catfish', 'Ictalurus punctatus'),
  ('Chinook Salmon', 'Oncorhynchus tshawytscha'),
  ('Chum Salmon', 'Oncorhynchus keta'),
  ('Clown Knifefish', 'Chitala ornata'),
  ('Coho Salmon', 'Oncorhynchus kisutch'),
  ('Croaker', 'Micropogonias undulatus'),
  ('Cubera Snapper', 'Lutjanus cyanopterus'),
  ('Cutthroat Trout', 'Oncorhynchus clarkii'),
  ('Dorado (Golden Dorado)', 'Salminus brasiliensis'),
  ('Flathead Catfish', 'Pylodictis olivaris'),
  ('Flounder', 'Paralichthys dentatus'),
  ('Freshwater Drum', 'Aplodinotus grunniens'),
  ('Gag Grouper', 'Mycteroperca microlepis'),
  ('Gar', 'Lepisosteidae'),
  ('Giant Snakehead', 'Channa micropeltes'),
  ('Giant Trevally', 'Caranx ignobilis'),
  ('Golden Trout', 'Oncorhynchus aguabonita'),
  ('Goliath Grouper', 'Epinephelus itajara'),
  ('Grass Carp', 'Ctenopharyngodon idella'),
  ('Great Hammerhead', 'Sphyrna mokarran'),
  ('Guadalupe Bass', 'Micropterus treculii'),
  ('Hybrid Bass', 'Morone saxatilis x Morone chrysops'),
  ('Jack Crevalle', 'Caranx hippos'),
  ('Juvenile Tarpon', 'Megalops atlanticus'),
  ('King Mackerel', 'Scomberomorus cavalla'),
  ('Lake Trout', 'Salvelinus namaycush'),
  ('Lane Snapper', 'Lutjanus synagris'),
  ('Largemouth Bass', 'Micropterus salmoides'),
  ('Lemon Shark', 'Negaprion brevirostris'),
  ('Mahi-Mahi', 'Coryphaena hippurus'),
  ('Mako Shark', 'Isurus oxyrinchus'),
  ('Mangrove Snapper', 'Lutjanus griseus'),
  ('Murray Cod', 'Maccullochella peelii'),
  ('Musky', 'Esox masquinongy'),
  ('Mutton Snapper', 'Lutjanus analis'),
  ('Nassau Grouper', 'Epinephelus striatus'),
  ('Nile Perch', 'Lates niloticus'),
  ('Northern Pike', 'Esox lucius'),
  ('Nurse Shark', 'Ginglymostoma cirratum'),
  ('Oscar', 'Astronotus ocellatus'),
  ('Pacu', 'Piaractus mesopotamicus'),
  ('Peacock Bass', 'Cichla ocellaris'),
  ('Peacock Grouper', 'Cephalopholis argus'),
  ('Pink Salmon', 'Oncorhynchus gorbuscha'),
  ('Pompano', 'Trachinotus carolinus'),
  ('Porgy', 'Sparidae'),
  ('Rainbow Trout', 'Oncorhynchus mykiss'),
  ('Red Grouper', 'Epinephelus morio'),
  ('Redear Sunfish', 'Lepomis microlophus'),
  ('Redfish', 'Sciaenops ocellatus'),
  ('Sailfish', 'Istiophorus platypterus'),
  ('Sandbar Shark', 'Carcharhinus plumbeus'),
  ('Scamp Grouper', 'Mycteroperca phenax'),
  ('Shoal Bass', 'Micropterus cataractae'),
  ('Skipjack Tuna', 'Katsuwonus pelamis'),
  ('Smallmouth Bass', 'Micropterus dolomieu'),
  ('Snook', 'Centropomus undecimalis'),
  ('Snowy Grouper', 'Hyporthodus niveatus'),
  ('Sockeye Salmon', 'Oncorhynchus nerka'),
  ('Spanish Mackerel', 'Scomberomorus maculatus'),
  ('Spearfish', 'Tetrapturus pfluegeri'),
  ('Speckled Trout', 'Cynoscion nebulosus'),
  ('Spinner Shark', 'Carcharhinus brevipinna'),
  ('Spot', 'Leiostomus xanthurus'),
  ('Spotted Bass', 'Micropterus punctulatus'),
  ('Stingray', 'Dasyatidae'),
  ('Striped Bass', 'Morone saxatilis'),
  ('Striped Marlin', 'Kajikia audax'),
  ('Thresher Shark', 'Alopias vulpinus'),
  ('Tiger Shark', 'Galeocerdo cuvier'),
  ('Tilapia', 'Oreochromis niloticus'),
  ('Tilefish', 'Lopholatilus chamaeleonticeps'),
  ('Trevally Species', 'Caranx spp.'),
  ('Triggerfish', 'Balistes capriscus'),
  ('Vermillion Snapper', 'Rhomboplites aurorubens'),
  ('White Bass', 'Morone chrysops'),
  ('White Catfish', 'Ameiurus catus'),
  ('White Marlin', 'Kajikia albida'),
  ('Whiting', 'Menticirrhus americanus'),
  ('Yellowfin Tuna', 'Thunnus albacares'),
  ('Yellowtail Snapper', 'Ocyurus chrysurus')
) AS data(name, sci)
WHERE public.fish_species.name = data.name
  AND (public.fish_species.scientific_name IS NULL OR public.fish_species.scientific_name = '');
